---
- name: Deploy static web application
  hosts: ec2_vm
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present

    - name: Ensure MySQL service is started
      systemd:
        name: mysql
        enabled: yes
        state: started

    - name: Copy database dump to the remote host
      copy:
        src: ./lamp-app/simple_lamp.sql
        dest: /tmp/simple_lamp.sql

    - name: Import MySQL database
      command: "mysql -u root  simple_lamp < /tmp/simple_lamp.sql"

    - name: Copy application files
      copy:
        src: ./lamp-app/
        dest: /var/www/html/
        owner: www-data
        group: www-data


    